#ifndef TEXTUREIDS_H
#define TEXTUREIDS_H

enum TEXTURE_ID
{
    MENU_BG_TEXTURE_ID,
    MENU_BTN_ABOUT_NORMAL_TEXTURE_ID,
    MENU_BTN_ABOUT_PRESSED_TEXTURE_ID,
    MENU_BTN_ABOUT_RELEASED_TEXTURE_ID
};

#endif // TEXTUREIDS_H
