#ifndef TEXTUREIDS_H
#define TEXTUREIDS_H

class TextureIDs
{
public:
    enum MENU_TEXTURE_ID
    {
        MENU_BG_TEXTURE_ID,
        MENU_BG_TEXT_HELLO,
        MENU_BTN_ABOUT_NORMAL_TEXTURE_ID,
        MENU_BTN_ABOUT_PRESSED_TEXTURE_ID,
        MENU_BTN_ABOUT_RELEASED_TEXTURE_ID
    };

};


#endif // TEXTUREIDS_H
